name = "mqpost"
main = "src/index.ts"
compatibility_date = "2022-07-07"
workers_dev = true
account_id = "4f296275a5fa3d5c36343151790e96d3"

[[queues.producers]]
queue = "mqpost"
binding = "MQPOST"

[[queues.producers]]
queue = "mqwaba"
binding = "MQWABA"

[[queues.consumers]]
queue = "mqpost"
max_batch_size = 1

[[r2_buckets]]
preview_bucket_name = "mqpostr2"
bucket_name = "mqpostr2"
binding = "MQPOSTR2"

[durable_objects]
bindings = [{ name = "MQPOSTDO", class_name = "MQPOSTDO" }]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["MQPOSTDO"]
