name = "mqpost"
main = "src/index.ts"
compatibility_date = "2024-01-12"
account_id = "4f296275a5fa3d5c36343151790e96d3"
workers_dev = true

routes = [
    { pattern = "mq.ideias.casa", custom_domain = true }
]

[[queues.producers]]
queue = "mqpost"
binding = "MQPOST"

[[queues.producers]]
queue = "mqemail"
binding = "MQEMAIL"

[[queues.producers]]
queue = "mqwaba"
binding = "MQWABA"

[[queues.producers]]
queue = "mqexpress"
binding = "MQEXPRESS"

[[queues.consumers]]
queue = "mqpost"
max_batch_size = 1

[[r2_buckets]]
preview_bucket_name = "mqpostr2"
bucket_name = "mqpostr2"
binding = "MQPOSTR2"
